### ISSUE TITLE
Usage in ESM project broken in v1.8.0

### ISSUE THREAD

**Issue by avaly** [contrawork/graphql-helix#62]
Starting with version 1.8.0 using this package in an ESM project is broken. The most likely commit which broke it is #47.

## Steps to reproduce

`package.json`:

```json
{
  "name": "graphql-helix-bugs",
  "type": "module",
  "dependencies": {
    "graphql": "15.6.0",
    "graphql-helix": "1.8.0"
  }
}
```

`index.js`:

```js
import { processRequest } from 'graphql-helix';

console.log(processRequest);
```

## Actual result

```
$ node index.js 
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /tmp/graphql-helix-bugs/node_modules/graphql-helix/package.json imported from /tmp/graphql-helix-bugs/index.js
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
    at packageResolve (internal/modules/esm/resolve.js:644:14)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

## Expected result

Downgrading to v1.7.0:

```
$ node index.js 
[AsyncFunction: processRequest]
```

**Comment by dotansimha** [comment]
@n1ru4l  @PabloSzx ideas?

**Comment by PabloSzx** [comment]
![Screenshot from 2021-09-24 12-43-59](https://user-images.githubusercontent.com/8672915/134703421-21f0e0bb-ccdc-4903-9a52-9523fcf491da.png)

the "exports" literally doesn't have any "import" field for ESM

**Comment by jvbianchi** [comment]
The change happened in this commit https://github.com/contrawork/graphql-helix/commit/185b64cbb76385bf4d7c9439c3bd45887326b645#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7

**Comment by dotansimha** [comment]
> ![Screenshot from 2021-09-24 12-43-59](https://user-images.githubusercontent.com/8672915/134703421-21f0e0bb-ccdc-4903-9a52-9523fcf491da.png)
> 
> the "exports" literally doesn't have any "import" field for ESM

Oh oops! I somehow forget to include some ESM changes from https://github.com/contrawork/graphql-helix/pull/44 

Working on a fix. Thank you
