### ISSUE TITLE
Update to support GraphQL JS v16

### ISSUE THREAD

**Issue by mcrawshaw** [contrawork/graphql-helix#87]
Hi,

After upgrading to GraphQL JS v16 (released [28th of Oct 2021](https://github.com/graphql/graphql-js/releases/tag/v16.0.0)) while using this library, you should receive this error.
```
 Must provide document.

      at devAssert (node_modules/graphql/jsutils/devAssert.js:12:11)
      at assertValidExecutionArguments (node_modules/graphql/execution/execute.js:145:40)
      at Object.execute (node_modules/graphql/execution/execute.js:74:3)
```

This is discussed in relation to other libraries here: https://github.com/graphql/graphql-js/issues/3245#issuecomment-906965808

The most critical change required would be to pass an object rather than params to `execute()`.

Mark.

**Comment by mcrawshaw** [comment]
Just noticed PR https://github.com/contrawork/graphql-helix/pull/84

**Comment by mcrawshaw** [comment]
Resolved, thanks!
